#!/bin/bash

Line_first='> '

Line_second='< '

Line_third='                                        '
Line_fifth='----------------------------------------'

for (( i=0; i<38; i++ )); do
end=$((37-i))
sleep 0.25
   echo -en "${Line_fifth:0:i}${Line_first:0:-1}${Line_third:0:end}commit${Line_third:0:end}${Line_second:0:-1}${Line_fifth:0:i}" "\r"
   #printf "\033[1A"
done
echo 
