#!/bin/bash

arr=( 
'****   *
 ***   **
 **   ***
 ***   **
 ****   *'
'****  * 
 ***  ** 
 **  *** 
 ***  ** 
 ****  * '
'**** *  
 *** **  
 *****  
 *** **  
 **** *  '
'*****  
 *****  
 *****  
 *****  
 *****  ' )

while [ 1 ]
do 
	for((i=0; i<=3; i++))
	do
		echo -ne "${arr[$i]}\n"
		sleep 0.5
		printf "\033[5A"
	done

	for((i=2; i>=0; i--))
	do
		echo -ne "${arr[$i]}\n"
		sleep 0.5
		printf "\033[5A"
	done

done
