#!/bin/bash

function triangle() {
    str="$1*"

    for i in 1 2 3 4 5 6
    do
        echo "$str"
        if [ ${i} -le 3 ]
        then
            str="$str*"
        else
            str=${str%?}
        fi
    done
    echo "$str"
}

function moveTo() {
    str=" "
    for i in {1..25}
    do
        str="${str} "
        triangle "${str}"
    sleep .5
    clear
    done
}

moveTo  
