#!/bin/bash

arr=( '****   *
***   **
**   ***
***   **
****   *' '****  * 
***  ** 
**  *** 
***  ** 
****  * ' '**** *  
*** **  
** ***  
*** **  
**** *  ' '*****  
*****  
*****  
*****  
*****  ' )

while [ 1 ]
do 
	for i in {0..3}
	do
		echo -ne "${arr[$i]}\n"
		sleep 0.5
		printf "\033[5A"
	done

	for i in {2..0}
	do
		echo -ne "${arr[$i]}\n"
		sleep 0.5
		printf "\033[5A"
	done

done

